export const chatConstants = {
	GET_ALL_MESSAGES_REQUEST: 'GET_ALL_MESSAGES_REQUEST',
	GET_ALL_MESSAGES_SUCCESS: 'GET_ALL_MESSAGES_SUCCESS',
	GET_ALL_MESSAGES_FAILURE: 'GET_ALL_MESSAGES_FAILURE',
	SUBMIT_MESSAGE_REQUEST: 'SUBMIT_MESSAGE_REQUEST',
	SUBMIT_MESSAGE_SUCCESS: 'SUBMIT_MESSAGE_SUCCESS',
	SUBMIT_MESSAGE_FAILURE: 'SUBMIT_MESSAGE_FAILURE',
	ADD_NEW_MESSAGE_SUCCESS: 'ADD_NEW_MESSAGE_SUCCESS'
};
